/*
 * This file has been auto-generated by CppUTestMock v0.3.1.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

#include "ExamplePrivateClass.hpp"

#include <CppUTestExt/MockSupport.h>

namespace expect { namespace ExamplePrivateClass$ {
MockExpectedCall& f2(CppUMockGen::Parameter<const ExamplePrivateClass*> __object__, CppUMockGen::Parameter<int> a, CppUMockGen::Parameter<int> b, int __return__);
MockExpectedCall& f2(unsigned int __numCalls__, CppUMockGen::Parameter<const ExamplePrivateClass*> __object__, CppUMockGen::Parameter<int> a, CppUMockGen::Parameter<int> b, int __return__);
} }

